name: deploy
on:
  push:
    branches: ["change-to-gleam"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.2.1"
          rebar3-version: "3"
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build site
        run: |
          gleam run -m lustre/dev -- build --minify
      - name: Copy files
        run: |
          mkdir _site
          cp -r priv _site
          cp index.html _site
          ls
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
